Update README.md
FYG-Solutions/Landing-Page-FYG pull request #4
Opened 2022-10-11 20:47 UTC by JesusdlaCruz

2022-10-11 20:50 UTC, RamsesMartinez requested changes

2022-10-11 20:50 UTC, RamsesMartinez commented on README.md
> +
Tu usario debe ir al final de la sección # Creator

2022-10-12 17:59 UTC, RamsesMartinez requested changes

2022-10-12 17:59 UTC, RamsesMartinez commented on README.md
> +
Eliminar esta línea que quedó de más

2022-10-12 17:59 UTC, RamsesMartinez commented
Adicionalmente, corregir conflictos

2022-10-12 23:41 UTC, JesusdlaCruz commented
Se agregó link personal de deployment en index.html y cambios en Readme.md

2022-10-12 23:47 UTC, Pati03 approved these changes

2022-10-13 02:23 UTC, JesusdlaCruz commented
Resolución de colisiones

2024-10-04 11:46 UTC, closed without merging